#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Sat Sep 19 14:40:48 ECT 2026
alwaysLogTamperWarnings=true
